test

diff --git a/checksec b/checksec
--- a/checksec
+++ b/checksec
@@ -80,9 +80,9 @@ FS_end=_chk
 FS_cnt_total=0
 FS_cnt_checked=0
 FS_cnt_unchecked=0
-FS_chk_func_libc=0
-FS_functions=0
-FS_libc=0
+FS_chk_func_libc=()
+FS_functions=()
+FS_result="no"
 
 # check for required files and deps first
 # check if command exists
@@ -479,38 +479,19 @@ filecheck() {
 
   # check for FORTIFY SOURCE
   ${debug} && echo "***function filecheck->fortify"
-  if [[ -e /lib/libc.so.6 ]] ; then
-    FS_libc=/lib/libc.so.6
-  elif [[ -e /lib/libc.so.7 ]] ; then
-    FS_libc=/lib/libc.so.7
-  elif [[ -e /lib/libc.so ]] ; then
-    FS_libc=/lib/libc.so
-  elif [[ -e /lib64/libc.so.6 ]] ; then
-    FS_libc=/lib64/libc.so.6
-  elif [[ -e /lib/i386-linux-gnu/libc.so.6 ]] ; then
-    FS_libc=/lib/i386-linux-gnu/libc.so.6
-  elif [[ -e /lib/x86_64-linux-gnu/libc.so.6 ]] ; then
-    FS_libc=/lib/x86_64-linux-gnu/libc.so.6
-  elif [[ -e /lib/arm-linux-gnueabihf/libc.so.6 ]] ; then
-    FS_libc=/lib/arm-linux-gnueabihf/libc.so.6
-  elif [[ -e /lib/aarch64-linux-gnu/libc.so.6 ]] ; then
-    FS_libc=/lib/aarch64-linux-gnu/libc.so.6
-  elif [[ -e /usr/x86_64-gentoo-linux-musl/bin/ld ]] ; then
-    FS_libc=/usr/x86_64-gentoo-linux-musl/bin/ld
-  else
-    printf "\033[31mError: libc not found.\033[m\n\n"
-    exit 1
-  fi
 
-  FS_chk_func_libc="$(${readelf} -s $FS_libc 2>/dev/null | sed -ne 's/.*__\(.*_chk\)@@.*/\1/p')"
+  FS_libc_init
   FS_func_libc="${FS_chk_func_libc//_chk/}"
-  FS_functions="$(${readelf} --dyn-syms "${1}" 2>/dev/null | awk '{ print $8 }' | sed -e 's/_*//' -e 's/@.*//' -e '/^$/d')"
-  FS_cnt_checked=$(grep -cFxf <(sort <<< "${FS_chk_func_libc}") <(sort <<< "${FS_functions}"))
-  FS_cnt_unchecked=$(grep -cFxf <(sort <<< "${FS_func_libc}") <(sort <<< "${FS_functions}"))
+
+  FS_internal_check "${1}"
+  FS_cnt_checked=$(grep -cFxf <(sort <<< "${FS_chk_func_libc[@]}") <(sort <<< "${FS_functions[@]}"))
+  FS_cnt_unchecked=$(grep -cFxf <(sort <<< "${FS_func_libc}") <(sort <<< "${FS_functions[@]}"))
   FS_cnt_total=$((FS_cnt_unchecked+FS_cnt_checked))
 
-  if grep -q '_chk$' <<<"$FS_functions"; then
+  if [[ "${FS_result}" == "yes" ]] ; then
     echo_message '\033[32mYes\033[m' 'Yes,' ' fortify_source="yes" ' '"fortify_source":"yes",'
+  elif [[ "${FS_result}" == "undecidable" ]] ; then
+    echo_message '\033[33mUndecidable\033[m' 'Undecidable,' ' fortify_source="undecidable" ' '"fortify_source":"undecidable",'
   else
     echo_message "\033[31mNo\033[m" "No," ' fortify_source="no" ' '"fortify_source":"no",'
   fi
@@ -641,9 +622,13 @@ proccheck() {
   fi 
 
   #check for forifty source support
-  FS_functions="$(${readelf} -s "${1}/exe" 2>/dev/null | awk '{ print $8 }' | sed 's/_*//' | sed -e 's/@.*//')"
-  if grep -q '_chk$' <<<"$FS_functions"; then
+  FS_libc_init
+  FS_internal_check "${1}/exe"
+
+  if [[ "${FS_result}" == "yes" ]] ; then
     echo_message '\033[32mYes\033[m' 'Yes' " fortify_source='yes'>" '"fortify_source":"yes" }'
+  elif [[ "${FS_result}" == "undecidable" ]] ; then
+    echo_message '\033[33mUndecidable\033[m' 'Undecidable' " fortify_source='undecidable'>" '"fortify_source":"undecidable" }'
   else
     echo_message "\033[31mNo\033[m" "No" " fortify_source='no'>" '"fortify_source":"no" }'
   fi
@@ -1387,6 +1372,43 @@ kernelcheck() {
 }
 
 # --- FORTIFY_SOURCE subfunctions (start) ---
+# load fortified functions from libs
+FS_libc_init() {
+  ${debug} && echo "***function FS_libc_init"
+
+  # already initialized?
+  if [[ "${#FS_chk_func_libc[@]}" -ne 0 ]] ; then
+    return
+  fi
+
+  if [[ -e /lib/libc.so.6 ]] ; then
+    libc=/lib/libc.so.6
+  elif [[ -e /lib/libc.so.7 ]] ; then
+    libc=/lib/libc.so.7
+  elif [[ -e /lib/libc.so ]] ; then
+    libc=/lib/libc.so
+  elif [[ -e /lib64/libc.so.6 ]] ; then
+    libc=/lib64/libc.so.6
+  elif [[ -e /lib/i386-linux-gnu/libc.so.6 ]] ; then
+    libc=/lib/i386-linux-gnu/libc.so.6
+  elif [[ -e /lib/x86_64-linux-gnu/libc.so.6 ]] ; then
+    libc=/lib/x86_64-linux-gnu/libc.so.6
+  elif [[ -e /lib/arm-linux-gnueabihf/libc.so.6 ]] ; then
+    libc=/lib/arm-linux-gnueabihf/libc.so.6
+  elif [[ -e /lib/aarch64-linux-gnu/libc.so.6 ]] ; then
+    libc=/lib/aarch64-linux-gnu/libc.so.6
+  elif [[ -e /usr/x86_64-gentoo-linux-musl/bin/ld ]] ; then
+    libc=/usr/x86_64-gentoo-linux-musl/bin/ld
+  else
+    printf "\033[31mError: libc not found.\033[m\n\n"
+    exit 1
+  fi
+
+  while IFS='' read -r line; do FS_chk_func_libc+=("$line"); done < <(${readelf} -s ${libc} 2>/dev/null | grep _chk@@ | awk '{ print $8 }' | cut -c 3- | sed -e 's/_chk@.*//')
+
+  FS_chk_func_libc=$(echo ${FS_chk_func_libc[@]} | sed 's/ /\n/g' | sort -u)
+}
+
 # is FORTIFY_SOURCE supported by libc?
 FS_libc_check() {
   ${debug} && echo "***function FS_libc_check"
@@ -1400,20 +1422,57 @@ FS_libc_check() {
   fi
 }
 
-# was the binary compiled with FORTIFY_SOURCE?
-FS_binary_check() {
-  ${debug} && echo "***function FS_binary_check"
-  echo_message "* Binary compiled with FORTIFY_SOURCE support: " "" "" ""
+FS_internal_check() {
+  ${debug} && echo "***function FS_internal_check ( ${1} )"
+
+  FS_functions=()
+  while IFS='' read -r line; do FS_functions+=("$line"); done < <(${readelf} -s "${1}" 2>/dev/null | awk '{ print $8 }' | sed 's/_*//' | sed -e 's/@.*//')
+
+  FS_functions=$(echo ${FS_functions[@]} | sed 's/ /\n/g' | sort -u)
+
+  local found_unfortified_call=0
 
   for ((FS_elem_functions=0; FS_elem_functions<${#FS_functions[@]}; FS_elem_functions++))
   do
     if [[ ${FS_functions[$FS_elem_functions]} =~ _chk$ ]] ; then
-      echo_message "\033[32mYes\033[m\n" "Yes\n" " binary_compiled_with_fortify='yes'>\n" ', "binary_compiled_with_fortify":"yes"'
+      FS_result="yes"
       return
     fi
+
+    if [[ $found_unfortified_call -eq 0 ]] ; then
+      for ((FS_elem_libc=0; FS_elem_libc<${#FS_chk_func_libc[@]}; FS_elem_libc++))
+      do
+        if [[ "${FS_functions[$FS_elem_functions]}" == "${FS_chk_func_libc[$FS_elem_libc]}" ]] ; then
+          found_unfortified_call=1
+        fi
+      done
+    fi
+
   done
-  echo_message "\033[31mNo\033[m\n" "No\n" " binary_compiled_with_fortify='no'>\n" ', "binary_compiled_with_fortify":"no"'
-  exit 1
+
+  if [[ $found_unfortified_call -eq 0 ]] ; then
+    FS_result="undecidable"
+    return
+  fi
+
+  FS_result="no"
+  return
+}
+
+# was the binary compiled with FORTIFY_SOURCE?
+FS_binary_check() {
+  ${debug} && echo "***function FS_binary_check ( ${1} )"
+  echo_message "* Binary compiled with FORTIFY_SOURCE support: " "" "" ""
+
+  FS_internal_check "${1}"
+
+  if [[ "${FS_result}" == "yes" ]] ; then
+    echo_message "\033[32mYes\033[m\n" "Yes\n" " binary_compiled_with_fortify='yes'>\n" ', "binary_compiled_with_fortify":"yes"'
+  elif [[ "${FS_result}" == "undecidable" ]] ; then
+    echo_message "\033[33mUndecidable\033[m\n" "Undecidable\n" " binary_compiled_with_fortify='undecidable'>\n" ', "binary_compiled_with_fortify":"undecidable"'
+  else
+    echo_message "\033[31mNo\033[m\n" "No\n" " binary_compiled_with_fortify='no'>\n" ', "binary_compiled_with_fortify":"no"'
+  fi
 }
 
 FS_comparison() {
@@ -1432,35 +1491,35 @@ FS_comparison() {
       FS_tmp_func=${FS_functions[$FS_elem_functions]}
       FS_tmp_libc=${FS_chk_func_libc[$FS_elem_libc]}
 
-  if [[ ${FS_tmp_func} =~ ^${FS_tmp_libc}$ ]] ; then
-    if [[ ${format} == "cli" ]]; then
-      printf " \033[31m%-30s\033[m | __%s%s\n" "${FS_tmp_func}" "${FS_tmp_libc}" "${FS_end}"
-    else
-      if [[ $FS_elem_functions == 0 ]]; then
-        echo_message "" "${FS_tmp_func},${FS_tmp_libc},yes\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='yes' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"yes\" }"
-      elif [[ $FS_elem_functions == $((${#FS_functions[@]} - 1 )) ]]; then
-        echo_message "" "${FS_tmp_func},${FS_tmp_libc},yes\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='yes' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"yes\" }"
-      else
-        echo_message "" "${FS_tmp_func},${FS_tmp_libc},yes\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='yes' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"yes\" }"
-    fi
-  fi
+      if [[ ${FS_tmp_func} =~ ^${FS_tmp_libc}$ ]] ; then
+        if [[ ${format} == "cli" ]]; then
+          printf " \033[31m%-30s\033[m | __%s%s\n" "${FS_tmp_func}" "${FS_tmp_libc}" "${FS_end}"
+        else
+          if [[ $FS_elem_functions == 0 ]]; then
+            echo_message "" "${FS_tmp_func},${FS_tmp_libc},yes\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='yes' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"yes\" }"
+          elif [[ $FS_elem_functions == $((${#FS_functions[@]} - 1 )) ]]; then
+            echo_message "" "${FS_tmp_func},${FS_tmp_libc},yes\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='yes' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"yes\" }"
+          else
+            echo_message "" "${FS_tmp_func},${FS_tmp_libc},yes\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='yes' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"yes\" }"
+          fi
+        fi
         (( FS_cnt_total++ ))
         (( FS_cnt_unchecked++ ))
-   elif [[ ${FS_tmp_func} =~ ^${FS_tmp_libc}(_chk)$ ]] ; then
-     if [[ ${format} == "cli" ]]; then
-       printf " \033[32m%-30s\033[m | __%s%s\n" "${FS_tmp_func}" "${FS_tmp_libc}" "${FS_end}"
-     else
-      if [[ $FS_elem_functions == 0 ]]; then
-        echo_message "" "${FS_tmp_func},${FS_tmp_libc},no\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='no' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"no\" }"
-      elif [[ $FS_elem_functions == $((${#FS_functions[@]} - 1 )) ]]; then
-        echo_message "" "${FS_tmp_func},${FS_tmp_libc},no\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='no' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"no\" }"
-      else
-        echo_message "" "${FS_tmp_func},${FS_tmp_libc},no\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='no' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"no\" }"
-      fi
-  fi
+      elif [[ ${FS_tmp_func} =~ ^${FS_tmp_libc}(_chk)$ ]] ; then
+        if [[ ${format} == "cli" ]]; then
+          printf " \033[32m%-30s\033[m | __%s%s\n" "${FS_tmp_func}" "${FS_tmp_libc}" "${FS_end}"
+        else
+          if [[ $FS_elem_functions == 0 ]]; then
+            echo_message "" "${FS_tmp_func},${FS_tmp_libc},no\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='no' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"no\" }"
+          elif [[ $FS_elem_functions == $((${#FS_functions[@]} - 1 )) ]]; then
+            echo_message "" "${FS_tmp_func},${FS_tmp_libc},no\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='no' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"no\" }"
+          else
+            echo_message "" "${FS_tmp_func},${FS_tmp_libc},no\n" "    <function name='${FS_tmp_func}' libc='${FS_tmp_libc}' fortifiable='no' />\n" ", \"function\": { \"name\":\"${FS_tmp_func}\", \"libc\":\"${FS_tmp_libc}\", \"fortifiable\":\"no\" }"
+          fi
+        fi
         (( FS_cnt_total++ ))
         (( FS_cnt_checked++ ))
-   fi
+      fi
 
     done
   done
@@ -1869,8 +1928,8 @@ chk_fortify_file () {
   fi
 
   if [[ -z "${CHK_FORTIFY_FILE}" ]] ; then
-    printf "\033[31mError: Please provide a valid file.\033[m\n\n"
-  exit 1
+    printf "\033[31mError: Please provide a valid file name.\033[m\n\n"
+    exit 1
   fi
   # does the file exist?
   if [[ ! -f "${CHK_FORTIFY_FILE}" ]] ; then
@@ -1891,30 +1950,10 @@ chk_fortify_file () {
     exit 1
   fi
 
-  if [[ -e /lib/libc.so.6 ]] ; then
-    FS_libc=/lib/libc.so.6
-  elif [[ -e /lib64/libc.so.6 ]] ; then
-    FS_libc=/lib64/libc.so.6
-  elif [[ -e /lib/i386-linux-gnu/libc.so.6 ]] ; then
-    FS_libc=/lib/i386-linux-gnu/libc.so.6
-  elif [[ -e /lib/x86_64-linux-gnu/libc.so.6 ]] ; then
-    FS_libc=/lib/x86_64-linux-gnu/libc.so.6
-  elif [[ -e /lib/arm-linux-gnueabihf/libc.so.6 ]] ; then
-    FS_libc=/lib/arm-linux-gnueabihf/libc.so.6
-  elif [[ -e /lib/aarch64-linux-gnu/libc.so.6 ]] ; then
-    FS_libc=/lib/aarch64-linux-gnu/libc.so.6
-  else
-    printf "\033[31mError: libc not found.\033[m\n\n"
-    exit 1
-  fi
-
-  FS_chk_func_libc=()
-  FS_functions=()
-  while IFS='' read -r line; do FS_chk_func_libc+=("$line"); done < <(${readelf} -s ${FS_libc} 2>/dev/null | grep _chk@@ | awk '{ print $8 }' | cut -c 3- | sed -e 's/_chk@.*//')
-  while IFS='' read -r line; do FS_functions+=("$line"); done < <(${readelf} -s "${CHK_FORTIFY_FILE}" 2>/dev/null | awk '{ print $8 }' | sed 's/_*//' | sed -e 's/@.*//')
   echo_message "" "" "<fortify-test name='${CHK_FORTIFY_FILE}' " "{ \"fortify-test\": { \"name\":\"${CHK_FORTIFY_FILE}\" "
+  FS_libc_init
   FS_libc_check
-  FS_binary_check
+  FS_binary_check "${CHK_FORTIFY_FILE}"
   FS_comparison
   FS_summary
   echo_message "" "" "</fortify-test>\n" "} }"
@@ -1944,28 +1983,14 @@ chk_fortify_proc () {
       fi
       exit 1
     fi
-    if [[ -e /lib/libc.so.6 ]] ; then
-      FS_libc=/lib/libc.so.6
-    elif [[ -e /lib64/libc.so.6 ]] ; then
-      FS_libc=/lib64/libc.so.6
-    elif [[ -e /lib/i386-linux-gnu/libc.so.6 ]] ; then
-      FS_libc=/lib/i386-linux-gnu/libc.so.6
-    elif [[ -e /lib/x86_64-linux-gnu/libc.so.6 ]] ; then
-      FS_libc=/lib/x86_64-linux-gnu/libc.so.6
-    else
-      printf "\033[31mError: libc not found.\033[m\n\n"
-      exit 1
-    fi
+
     name=$(head -1 "${N}/status" | cut -b 7-)
     echo_message  "* Process name (PID)                         : ${name} (${N})\n" "" "" ""
 
-    FS_chk_func_libc=()
-    FS_functions=()
-    while IFS='' read -r line; do FS_chk_func_libc+=("$line"); done < <(${readelf} -s $FS_libc 2>/dev/null | grep _chk@@ | awk '{ print $8 }' | cut -c 3- | sed -e 's/_chk@.*//')
-    while IFS='' read -r line; do FS_functions+=("$line"); done < <(${readelf} -s "${CHK_FORTIFY_PROC}/exe" 2>/dev/null | awk '{ print $8 }' | sed 's/_*//' | sed -e 's/@.*//')
     echo_message "" "" "<fortify-test name='${name}' pid='${N}' " "{ \"fortify-test\": { \"name\":\"${name}\", \"pid\":\"${N}\" "
+    FS_libc_init
     FS_libc_check
-    FS_binary_check
+    FS_binary_check "${N}/exe"
     FS_comparison
     FS_summary
     echo_message "" "" "</fortify-test>\n" "} }"
